# Udacity's AWS AI ML Course Project I
<hr/>

## Submitted by Abhijith Ganesh

[Kaggle Link](https://www.kaggle.com/c/bike-sharing-demand/overview)

Uses AutoGluon

In [21]:
!pip install -U pandas scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/abhijithganesh/.local/lib/python3.11/site-packages (2.0.1)
Requirement already satisfied: scikit-learn in /home/abhijithganesh/.local/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from pandas) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/abhijithganesh/.local/lib/python3.11/site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [27]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from datetime import datetime
import os

In [23]:
# Get current directory pathlib

directory = os.getcwd() + "/dataset"
test_set = pd.read_csv(directory + "/test.csv")
train_set = pd.read_csv(directory + "/train.csv")

In [24]:
test_set.describe()

,season,holiday,workingday,weather,temp,atemp,humidity,windspeed
count,6493.000000,6493.000000,6493.000000,6493.000000,6493.000000,6493.000000,6493.000000,6493.000000
mean,2.493300,0.029108,0.685815,1.436778,20.620607,24.012865,64.125212,12.631157
std,1.091258,0.168123,0.464226,0.648390,8.059583,8.782741,19.293391,8.250151
min,1.000000,0.000000,0.000000,1.000000,0.820000,0.000000,16.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,13.940000,16.665000,49.000000,7.001500
50%,3.000000,0.000000,1.000000,1.000000,21.320000,25.000000,65.000000,11.001400
75%,3.000000,0.000000,1.000000,2.000000,27.060000,31.060000,81.000000,16.997900
max,4.000000,1.000000,1.000000,4.000000,40.180000,50.000000,100.000000,55.998600

In [25]:
test_set.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed
0,2011-01-20 00:00:00,1,0,1,1,10.66,11.365,56,26.0027
1,2011-01-20 01:00:00,1,0,1,1,10.66,13.635,56,0.0000
2,2011-01-20 02:00:00,1,0,1,1,10.66,13.635,56,0.0000
3,2011-01-20 03:00:00,1,0,1,1,10.66,12.880,56,11.0014
4,2011-01-20 04:00:00,1,0,1,1,10.66,12.880,56,11.0014

In [30]:
test_set["datetime"] = pd.to_datetime(test_set["datetime"])

## Notes from the dataset

- The dataset has only one variable stored as string (datetime) and it needs to be converted to datetime format

## Null Values exist in:
- Windspeed

In [31]:
test_set.corr()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed
datetime,1.000000,0.275389,0.020884,-0.003417,-0.030518,0.061189,0.064187,-0.034914,-0.052798
season,0.275389,1.000000,-0.075759,0.051488,-0.053554,0.401384,0.410626,0.083792,-0.154507
holiday,0.020884,-0.075759,1.000000,-0.255820,-0.033279,-0.071852,-0.072373,-0.031611,-0.003240
workingday,-0.003417,0.051488,-0.255820,1.000000,0.062447,0.096519,0.103202,0.059599,-0.053690
weather,-0.030518,-0.053554,-0.033279,0.062447,1.000000,-0.179034,-0.185746,0.437406,0.057360
temp,0.061189,0.401384,-0.071852,0.096519,-0.179034,1.000000,0.991936,-0.081734,-0.030990
atemp,0.064187,0.410626,-0.072373,0.103202,-0.185746,0.991936,1.000000,-0.068666,-0.069655
humidity,-0.034914,0.083792,-0.031611,0.059599,0.437406,-0.081734,-0.068666,1.000000,-0.242708
windspeed,-0.052798,-0.154507,-0.003240,-0.053690,0.057360,-0.030990,-0.069655,-0.242708,1.000000